version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    
volumes:
  db:
    driver: local